// Package floats provides SIMD-accelerated reductions over float32 and float64
// slices — the dot product, sum, min, max, Euclidean (L2) distance and cosine
// similarity that sit at the heart of vector search, embeddings and numerics.
// It is pure Go (CGO_ENABLED=0, stable Go, no GOEXPERIMENT): the hot reduction
// loops are SIMD assembly generated by go-asmgen on all six of Go's 64-bit
// SIMD targets — amd64 (AVX2+FMA), arm64 (NEON FMLA), ppc64le (VSX), s390x
// (vector facility), riscv64 (RVV) and loong64 (LSX) — with a portable scalar
// fallback everywhere else, all on a plain `go build`.
//
// # Operations
//
// For both []float32 (the Float32 functions) and []float64:
//
//	Dot(a, b)              a·b = Σ aᵢbᵢ
//	Sum(a)                 Σ aᵢ
//	Min(a) / Max(a)        the minimum / maximum element
//	Distance(a, b)         ‖a−b‖₂ = √Σ(aᵢ−bᵢ)²
//	CosineSimilarity(a, b) a·b / (‖a‖₂‖b‖₂)
//
// Dot, Distance and CosineSimilarity require len(a) == len(b) and panic
// otherwise. Min and Max panic on an empty slice. Sum of an empty slice is 0.
//
// # Floating-point determinism
//
// A SIMD reduction does not add its terms left-to-right: it keeps several
// independent accumulator lanes (for instruction-level parallelism) and folds
// them together at the end, so the rounding differs from a naïve scalar loop.
// To stay deterministic and architecture-independent, the scalar reference used
// internally and by the tests (sumLanes / dotLanes / …) reduces in the *same*
// lane-blocked order the kernels use (laneCount lanes), and the SIMD result is
// required to agree with it to a tight, documented ULP bound across every
// architecture (the differential tests and FuzzDot/FuzzDistance enforce this).
// For the similarity use case (cosine / Euclidean distance) bit-exact equality
// with a naïve scalar loop is neither required nor meaningful; correctness to a
// few ULP is.
package floats

import "math"

// laneCount is the number of independent accumulator lanes the lane-blocked
// scalar reference folds over. The SIMD kernels are generated to reduce in the
// same lane structure, so their results agree with the reference to within a
// small ULP bound regardless of architecture.
const laneCount = 8

// Dot returns the dot product a·b = Σ aᵢbᵢ. It panics if len(a) != len(b).
func Dot(a, b []float64) float64 {
	if len(a) != len(b) {
		panic("floats: slice length mismatch")
	}
	return dot(a, b)
}

// Sum returns Σ aᵢ. The sum of an empty slice is 0.
func Sum(a []float64) float64 { return sum(a) }

// Min returns the smallest element of a. It panics if a is empty. If a contains
// a NaN the result is NaN.
func Min(a []float64) float64 {
	if len(a) == 0 {
		panic("floats: Min of empty slice")
	}
	m := a[0]
	for _, v := range a[1:] {
		if v < m || math.IsNaN(v) {
			m = v
		}
	}
	return m
}

// Max returns the largest element of a. It panics if a is empty. If a contains
// a NaN the result is NaN.
func Max(a []float64) float64 {
	if len(a) == 0 {
		panic("floats: Max of empty slice")
	}
	m := a[0]
	for _, v := range a[1:] {
		if v > m || math.IsNaN(v) {
			m = v
		}
	}
	return m
}

// Distance returns the Euclidean (L2) distance ‖a−b‖₂ = √Σ(aᵢ−bᵢ)². It panics
// if len(a) != len(b).
func Distance(a, b []float64) float64 {
	if len(a) != len(b) {
		panic("floats: slice length mismatch")
	}
	return math.Sqrt(sumSqDiff(a, b))
}

// CosineSimilarity returns a·b / (‖a‖₂‖b‖₂), a value in [-1, 1] measuring the
// angle between a and b — the standard relevance score for embedding vectors.
// It panics if len(a) != len(b). If either vector has zero magnitude the result
// is NaN (0/0), matching the mathematical definition.
func CosineSimilarity(a, b []float64) float64 {
	if len(a) != len(b) {
		panic("floats: slice length mismatch")
	}
	d := dot(a, b)
	na := dot(a, a)
	nb := dot(b, b)
	return d / math.Sqrt(na*nb)
}
