//go:build amd64

package floats

import "golang.org/x/sys/cpu"

// AVX2+FMA reduction kernels, generated by go-asmgen (kernels_amd64_gen.go) into
// kernels_amd64.s. Each folds the slice into a YMM accumulator with VFMADD231P*
// / VADDP* and a scalar tail, then horizontally reduces to the scalar result.
func dotAVX2(a, b []float64) float64
func sumAVX2(a []float64) float64
func sumSqDiffAVX2(a, b []float64) float64
func dot32AVX2(a, b []float32) float32
func sum32AVX2(a []float32) float32
func sumSqDiff32AVX2(a, b []float32) float32

// hasAVX2FMA gates the AVX2 path; both AVX2 and FMA3 are required (VFMADD231*).
// Almost every x86-64 part since Haswell (2013) has both. Without them the
// kernels would #UD, so the dispatcher falls back to the lane-blocked scalar
// reference.
var hasAVX2FMA = cpu.X86.HasAVX2 && cpu.X86.HasFMA

func dot(a, b []float64) float64 {
	if hasAVX2FMA {
		return dotAVX2(a, b)
	}
	return dotLanes(a, b)
}

func sum(a []float64) float64 {
	if hasAVX2FMA {
		return sumAVX2(a)
	}
	return sumLanes(a)
}

func sumSqDiff(a, b []float64) float64 {
	if hasAVX2FMA {
		return sumSqDiffAVX2(a, b)
	}
	return sumSqDiffLanes(a, b)
}

func dot32(a, b []float32) float32 {
	if hasAVX2FMA {
		return dot32AVX2(a, b)
	}
	return dotLanes32(a, b)
}

func sum32(a []float32) float32 {
	if hasAVX2FMA {
		return sum32AVX2(a)
	}
	return sumLanes32(a)
}

func sumSqDiff32(a, b []float32) float32 {
	if hasAVX2FMA {
		return sumSqDiff32AVX2(a, b)
	}
	return sumSqDiffLanes32(a, b)
}
