// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·dotVX(SB), NOSPLIT, $0-56
	MOVD a_base+0(FP), R1
	MOVD a_len+8(FP), R2
	MOVD b_base+24(FP), R3
	VZERO V0
	MOVD $0, R4
vloop:
	ADD $2, R4, R5
	CMPBGT R5, R2, vtail
	SLD $3, R4, R6
	VL (R1)(R6*1), V1
	VL (R3)(R6*1), V2
	VFMADB V1, V2, V0, V0
	ADD $2, R4, R4
	BR vloop
vtail:
	VLGVG $0, V0, R7
	VLGVG $1, V0, R8
	LDGR R7, F0
	LDGR R8, F1
	FADD F1, F0
sloop:
	CMPBGE R4, R2, done
	SLD $3, R4, R6
	FMOVD (R1)(R6*1), F1
	FMOVD (R3)(R6*1), F2
	FMADD F1, F2, F0
	ADD $1, R4, R4
	BR sloop
done:
	FMOVD F0, ret+48(FP)
	RET

TEXT ·sumVX(SB), NOSPLIT, $0-32
	MOVD a_base+0(FP), R1
	MOVD a_len+8(FP), R2
	VZERO V0
	MOVD $0, R4
vloop:
	ADD $2, R4, R5
	CMPBGT R5, R2, vtail
	SLD $3, R4, R6
	VL (R1)(R6*1), V1
	VFADB V1, V0, V0
	ADD $2, R4, R4
	BR vloop
vtail:
	VLGVG $0, V0, R7
	VLGVG $1, V0, R8
	LDGR R7, F0
	LDGR R8, F1
	FADD F1, F0
sloop:
	CMPBGE R4, R2, done
	SLD $3, R4, R6
	FMOVD (R1)(R6*1), F1
	FADD F1, F0
	ADD $1, R4, R4
	BR sloop
done:
	FMOVD F0, ret+24(FP)
	RET

TEXT ·sumSqDiffVX(SB), NOSPLIT, $0-56
	MOVD a_base+0(FP), R1
	MOVD a_len+8(FP), R2
	MOVD b_base+24(FP), R3
	VZERO V0
	MOVD $0, R4
vloop:
	ADD $2, R4, R5
	CMPBGT R5, R2, vtail
	SLD $3, R4, R6
	VL (R1)(R6*1), V1
	VL (R3)(R6*1), V2
	VFSDB V2, V1, V3
	VFMADB V3, V3, V0, V0
	ADD $2, R4, R4
	BR vloop
vtail:
	VLGVG $0, V0, R7
	VLGVG $1, V0, R8
	LDGR R7, F0
	LDGR R8, F1
	FADD F1, F0
sloop:
	CMPBGE R4, R2, done
	SLD $3, R4, R6
	FMOVD (R1)(R6*1), F1
	FMOVD (R3)(R6*1), F2
	FSUB F2, F1
	FMADD F1, F1, F0
	ADD $1, R4, R4
	BR sloop
done:
	FMOVD F0, ret+48(FP)
	RET

