//go:build s390x

package floats

// z/Architecture vector-facility FMA kernels for float64, generated by
// go-asmgen (kernels_s390x_gen.go) into kernels_s390x.s. The vector facility is
// the z13 baseline, so these are used unconditionally.
//
// float32 is not vectorised here — the released assembler lacks the single-
// element (.SB) vector-FP mnemonics — so the float32 reductions use the
// lane-blocked scalar reference, which the compiler pipelines well.
func dotVX(a, b []float64) float64
func sumVX(a []float64) float64
func sumSqDiffVX(a, b []float64) float64

func dot(a, b []float64) float64       { return dotVX(a, b) }
func sum(a []float64) float64          { return sumVX(a) }
func sumSqDiff(a, b []float64) float64 { return sumSqDiffVX(a, b) }

func dot32(a, b []float32) float32       { return dotLanes32(a, b) }
func sum32(a []float32) float32          { return sumLanes32(a) }
func sumSqDiff32(a, b []float32) float32 { return sumSqDiffLanes32(a, b) }
