//go:build loong64

package floats

// LSX has 128-bit vector registers (2 float64s per VMOVQ / VFMADDD). The
// hand-written kernel routed dot/sum/sumSqDiff through two-lane FMAs with a
// single V0 accumulator (serial dep chain on VFMADDD), which is the exact
// pattern that lost to the Go compiler's autovectorized naive scalar on
// s390x VXE2 (see kernels_s390x.go for the same story + the real z15
// measurement showing 11.8 → 20.6 GB/s just by routing to the naive loop).
//
// Same reasoning holds on LA464: the Go compiler on loong64 recognises the
// textbook `s += a[i] * b[i]` shape and generates a wider unrolled LSX
// pipeline than the 2-lane hand-asm kernel with its serial FMA dep can hit.
// Route loong64 through inline naive-shape loops for now — the compiler-loved
// pattern wins on this micro-architecture too.
//
// A wider hand-asm kernel with 4-8 independent V-register accumulators
// could still overtake autovector; leaving that for a later revisit via
// go-asmgen. The float32 kernels stay as-is (they use LSX for a wider
// lane count and win against naive on their pattern).

func dot(a, b []float64) float64 {
	var s float64
	for i := range a {
		s += a[i] * b[i]
	}
	return s
}

func sum(a []float64) float64 {
	var s float64
	for i := range a {
		s += a[i]
	}
	return s
}

func sumSqDiff(a, b []float64) float64 {
	var s float64
	for i := range a {
		d := a[i] - b[i]
		s += d * d
	}
	return s
}

func dot32(a, b []float32) float32       { return dot32LSX(a, b) }
func sum32(a []float32) float32          { return sum32LSX(a) }
func sumSqDiff32(a, b []float32) float32 { return sumSqDiff32LSX(a, b) }

// The float32 LSX kernels are kept — they hit 4 lanes per VMOVQ (128-bit /
// 32-bit) so their multi-lane parallelism outweighs the single-accumulator
// dep chain that hurt float64. Generated by go-asmgen into kernels_loong64.s.
func dot32LSX(a, b []float32) float32
func sum32LSX(a []float32) float32
func sumSqDiff32LSX(a, b []float32) float32
