//go:build riscv64

package floats

import "golang.org/x/sys/cpu"

// RVV reduction kernels, generated by go-asmgen (kernels_riscv64_gen.go) into
// kernels_riscv64.s. They use VSETVLI stripmining (no scalar tail) with
// VFMUL/VFSUB + an ordered VFREDOSUMVS per chunk.
func dotRVV(a, b []float64) float64
func sumRVV(a []float64) float64
func sumSqDiffRVV(a, b []float64) float64
func dot32RVV(a, b []float32) float32
func sum32RVV(a []float32) float32
func sumSqDiff32RVV(a, b []float32) float32

// hasRVV gates the vector path on the RVV 1.0 extension; pre-RVV hardware (and
// qemu without v=true) falls back to the lane-blocked scalar reference.
var hasRVV = cpu.RISCV64.HasV

func dot(a, b []float64) float64 {
	if hasRVV {
		return dotRVV(a, b)
	}
	return dotLanes(a, b)
}

func sum(a []float64) float64 {
	if hasRVV {
		return sumRVV(a)
	}
	return sumLanes(a)
}

func sumSqDiff(a, b []float64) float64 {
	if hasRVV {
		return sumSqDiffRVV(a, b)
	}
	return sumSqDiffLanes(a, b)
}

func dot32(a, b []float32) float32 {
	if hasRVV {
		return dot32RVV(a, b)
	}
	return dotLanes32(a, b)
}

func sum32(a []float32) float32 {
	if hasRVV {
		return sum32RVV(a)
	}
	return sumLanes32(a)
}

func sumSqDiff32(a, b []float32) float32 {
	if hasRVV {
		return sumSqDiff32RVV(a, b)
	}
	return sumSqDiffLanes32(a, b)
}
