//go:build ppc64le

package floats

// VSX FMA reduction kernels, generated by go-asmgen (kernels_ppc64le_gen.go)
// into kernels_ppc64le.s. VSX is the POWER8 baseline, so these are used
// unconditionally (no runtime feature gate).
func dotVSX(a, b []float64) float64
func sumVSX(a []float64) float64
func sumSqDiffVSX(a, b []float64) float64
func dot32VSX(a, b []float32) float32
func sum32VSX(a []float32) float32
func sumSqDiff32VSX(a, b []float32) float32

func dot(a, b []float64) float64       { return dotVSX(a, b) }
func sum(a []float64) float64          { return sumVSX(a) }
func sumSqDiff(a, b []float64) float64 { return sumSqDiffVSX(a, b) }

func dot32(a, b []float32) float32       { return dot32VSX(a, b) }
func sum32(a []float32) float32          { return sum32VSX(a) }
func sumSqDiff32(a, b []float32) float32 { return sumSqDiff32VSX(a, b) }
