//go:build arm64

package floats

// NEON FMA reduction kernels, generated by go-asmgen (kernels_arm64_gen.go) into
// kernels_arm64.s. NEON is part of the ARMv8-A baseline, so there is no runtime
// feature gate — these are used unconditionally on arm64.
func dotNEON(a, b []float64) float64
func sumNEON(a []float64) float64
func sumSqDiffNEON(a, b []float64) float64
func dot32NEON(a, b []float32) float32
func sum32NEON(a []float32) float32
func sumSqDiff32NEON(a, b []float32) float32

func dot(a, b []float64) float64       { return dotNEON(a, b) }
func sum(a []float64) float64          { return sumNEON(a) }
func sumSqDiff(a, b []float64) float64 { return sumSqDiffNEON(a, b) }

func dot32(a, b []float32) float32       { return dot32NEON(a, b) }
func sum32(a []float32) float32          { return sum32NEON(a) }
func sumSqDiff32(a, b []float32) float32 { return sumSqDiff32NEON(a, b) }
