//go:build ppc64le

package floats

import "golang.org/x/sys/cpu"

// VSX FMA reduction kernels, generated by go-asmgen (kernels_ppc64le_gen.go)
// into kernels_ppc64le.s. The kernels emit ISA-3.0 (POWER9) instructions
// (e.g. MFVSRLD), which raise SIGILL on POWER8, so they run only when hasVSX
// reports POWER9+; on POWER8 the lane-blocked scalar reference (reference.go)
// does the work.
func dotVSX(a, b []float64) float64
func sumVSX(a []float64) float64
func sumSqDiffVSX(a, b []float64) float64
func dot32VSX(a, b []float32) float32
func sum32VSX(a []float32) float32
func sumSqDiff32VSX(a, b []float32) float32

// hasVSX gates the generated kernels. They use ISA-3.0 (POWER9) VSX
// instructions (e.g. MFVSRLD) that are illegal on POWER8, so the kernels run
// only on POWER9+; otherwise the scalar reference is used. It is a var (not a
// const) so the dispatch test can also drive the fallback.
var hasVSX = cpu.PPC64.IsPOWER9

func dot(a, b []float64) float64 {
	if hasVSX {
		return dotVSX(a, b)
	}
	return dotLanes(a, b)
}

func sum(a []float64) float64 {
	if hasVSX {
		return sumVSX(a)
	}
	return sumLanes(a)
}

func sumSqDiff(a, b []float64) float64 {
	if hasVSX {
		return sumSqDiffVSX(a, b)
	}
	return sumSqDiffLanes(a, b)
}

func dot32(a, b []float32) float32 {
	if hasVSX {
		return dot32VSX(a, b)
	}
	return dotLanes32(a, b)
}

func sum32(a []float32) float32 {
	if hasVSX {
		return sum32VSX(a)
	}
	return sumLanes32(a)
}

func sumSqDiff32(a, b []float32) float32 {
	if hasVSX {
		return sumSqDiff32VSX(a, b)
	}
	return sumSqDiffLanes32(a, b)
}
