//go:build riscv64

package floats

import "golang.org/x/sys/cpu"

// The RVV 1.0 kernels below (dotRVV, sumRVV, sumSqDiffRVV, and the float32
// siblings) are compiled from kernels_riscv64.s. They're used when the CPU
// actually advertises the V extension AND when they beat the compiler's
// autovectorised reference — that second condition is where riscv64 currently
// SIGNALS TROUBLE for float64:
//
// On the SpacemiT X60 (RVV 1.0, in-order core; the only widely-shipped RVV
// silicon as of 2026-07) the naive scalar `s += a[i] * b[i]` loop measured
// 2166 – 2500 MB/s across Dot/8 → Dot/4096; the hand-asm RVV kernel measured
// 1209 – 2264 MB/s across the same range — a 0.56–0.91× LOSS at every size,
// same shape of gap the s390x and loong64 kernels showed (single accumulator
// + serial VFREDOSUMVS dep chain).
//
// Route float64 through inline naive-shape loops for now: same fix pattern
// as [go-simd/floats#3] (s390x) and [go-simd/floats#7] (loong64). float32
// stays on the hand-asm path — the RVV kernel groups 8 float32 lanes into a
// v-reg group with independent partial sums, which the compiler's autovector
// cannot yet match on riscv64.
//
// A future RVV kernel with more independent v-reg accumulators could beat
// autovector; that's a go-asmgen extension separate from this fix.

// dot32RVV / sum32RVV / sumSqDiff32RVV are the float32 RVV kernels — kept
// as-is because the 8-lane grouping wins vs the compiler's autovector.
// Generated by go-asmgen into kernels_riscv64.s.
func dot32RVV(a, b []float32) float32
func sum32RVV(a []float32) float32
func sumSqDiff32RVV(a, b []float32) float32

// hasRVV gates the float32 RVV path on the RVV 1.0 extension; pre-RVV
// hardware (and qemu without v=true) falls back to the lane-blocked scalar
// reference. float64 no longer consults this flag because the naive-shape
// loop is the winner at every size on real RVV silicon.
var hasRVV = cpu.RISCV64.HasV

func dot(a, b []float64) float64 {
	var s float64
	for i := range a {
		s += a[i] * b[i]
	}
	return s
}

func sum(a []float64) float64 {
	var s float64
	for i := range a {
		s += a[i]
	}
	return s
}

func sumSqDiff(a, b []float64) float64 {
	var s float64
	for i := range a {
		d := a[i] - b[i]
		s += d * d
	}
	return s
}

func dot32(a, b []float32) float32 {
	if hasRVV {
		return dot32RVV(a, b)
	}
	return dotLanes32(a, b)
}

func sum32(a []float32) float32 {
	if hasRVV {
		return sum32RVV(a)
	}
	return sumLanes32(a)
}

func sumSqDiff32(a, b []float32) float32 {
	if hasRVV {
		return sumSqDiff32RVV(a, b)
	}
	return sumSqDiffLanes32(a, b)
}
