//go:build s390x

package floats

// z/Architecture vector-facility FMA kernels for float64, generated by
// go-asmgen (kernels_s390x_gen.go) into kernels_s390x.s. The vector facility is
// the z13 baseline, so these are used unconditionally.
//
// float32 is not vectorised here — the released assembler lacks the single-
// element (.SB) vector-FP mnemonics — so the float32 reductions use the
// lane-blocked scalar reference, which the compiler pipelines well.
//
// float64 Dot has NO VX kernel here, deliberately. On real z15 silicon
// (linux1, go1.26.4, 2026-07-03) the VFMADB dot-product kernel is SLOWER than
// the plain Go loop the gc compiler already autovectorizes — measured Dot
// throughput VX vs naive 11.6 GB/s vs 20.6 GB/s = 0.56×. Per the dispatch
// principle (never run a SIMD kernel where it loses to the scalar/autovectorized
// path) Dot routes to the naive autovectorizable loop below, so no dot kernel is
// generated. Sum and SumSqDiff KEEP their VX kernels: they were not measured as
// losses on z15, and Distance/CosineSimilarity build on them.
//
// We deliberately do NOT use the lane-blocked reference (reference.go) for the
// s390x Dot: its multi-lane fold defeats the gc autovectorizer, so the plain
// left-to-right loop is the faster scalar form (same rationale as ppc64le).
func sumVX(a []float64) float64
func sumSqDiffVX(a, b []float64) float64

func dot(a, b []float64) float64 {
	var s float64
	for i := range a {
		s += a[i] * b[i]
	}
	return s
}

func sum(a []float64) float64          { return sumVX(a) }
func sumSqDiff(a, b []float64) float64 { return sumSqDiffVX(a, b) }

func dot32(a, b []float32) float32       { return dotLanes32(a, b) }
func sum32(a []float32) float32          { return sumLanes32(a) }
func sumSqDiff32(a, b []float32) float32 { return sumSqDiffLanes32(a, b) }
