//go:build loong64

package floats

// LSX FMA reduction kernels, generated by go-asmgen (kernels_loong64_gen.go)
// into kernels_loong64.s. LSX is the LA464 baseline, so these are used
// unconditionally (no runtime feature gate).
func dotLSX(a, b []float64) float64
func sumLSX(a []float64) float64
func sumSqDiffLSX(a, b []float64) float64
func dot32LSX(a, b []float32) float32
func sum32LSX(a []float32) float32
func sumSqDiff32LSX(a, b []float32) float32

func dot(a, b []float64) float64       { return dotLSX(a, b) }
func sum(a []float64) float64          { return sumLSX(a) }
func sumSqDiff(a, b []float64) float64 { return sumSqDiffLSX(a, b) }

func dot32(a, b []float32) float32       { return dot32LSX(a, b) }
func sum32(a []float32) float32          { return sum32LSX(a) }
func sumSqDiff32(a, b []float32) float32 { return sumSqDiff32LSX(a, b) }
